export async function renderAdminOverview(target, token, esc) {
  target.innerHTML = '<p role="status">Caricamento abbonamenti e richieste…</p>';
  try {
    const response = await fetch('/api/admin/p2p-overview', { headers: { Authorization: `Bearer ${token}` } });
    if (!response.ok) throw new Error('Impossibile caricare il riepilogo. Verifica la sessione e riprova.');
    const data = await response.json();
    const date = value => value ? new Date(value).toLocaleDateString('it-IT') : '—';
    const statuses = { active:'Attivo', inactive:'Non attivo', pending:'In attesa', past_due:'Pagamento da verificare', canceled:'Cancellato', suspended:'Sospeso', confirmed:'Confermato dal capogruppo', accepted:'Posto riservato', reported:'Pagamento dichiarato dal membro', expired:'Scaduto', cancelled:'Annullato', rejected:'Rifiutato' };
    target.innerHTML = `<section class="billing-card"><h2>Accessi BYS e quote dei gruppi</h2><p><strong>${data.activeCount}</strong> accessi attivi · <strong>${data.attentionCount}</strong> abbonamenti da verificare.</p><p>L’accesso BYS costa 0,99 €/mese. Le quote sono pagate direttamente al capogruppo: le conferme qui riportate non certificano un incasso BYS.</p><button type="button" id="refreshAdminOverview" class="btn btn-secondary">Aggiorna riepilogo</button></section>
    <section class="billing-card"><h3>Abbonamenti di accesso (${data.subscriptions.length})</h3><div style="overflow-x:auto"><table class="admin-overview-table"><thead><tr><th>Utente</th><th>Stato</th><th>Periodo fino al</th><th>Rinnovo</th><th>Riferimento PayPal</th></tr></thead><tbody>${data.subscriptions.map(s=>`<tr><td>${esc(s.name)}<br><small>${esc(s.email)}</small></td><td>${esc(statuses[s.status] || s.status)}</td><td>${esc(date(s.currentPeriodEnd))}</td><td>${s.cancelAtPeriodEnd ? 'Disattivato' : s.accessAllowed ? 'Automatico' : 'Da verificare'}</td><td>${esc(s.providerSubscriptionId || '—')}</td></tr>`).join('') || '<tr><td colspan="5">Nessun abbonamento registrato.</td></tr>'}</tbody></table></div></section>
    <section class="billing-card"><h3>Richieste e quote (${data.requests.length})</h3><div style="overflow-x:auto"><table class="admin-overview-table"><thead><tr><th>Gruppo</th><th>Membro</th><th>Capogruppo</th><th>Stato</th><th>Quota</th><th>Periodo fino al</th></tr></thead><tbody>${data.requests.map(r=>`<tr><td>${esc(r.groupName)}</td><td>${esc(r.member)}</td><td>${esc(r.leader)}</td><td>${esc(statuses[r.status] || r.status)}</td><td>${esc(((r.amountCents || 0)/100).toLocaleString('it-IT',{style:'currency',currency:'EUR'}))}</td><td>${esc(date(r.periodEnd))}</td></tr>`).join('') || '<tr><td colspan="6">Nessuna richiesta registrata.</td></tr>'}</tbody></table></div></section>`;
    target.querySelector('#refreshAdminOverview').onclick = () => renderAdminOverview(target, token, esc);
  } catch (error) { target.innerHTML = `<p role="alert">${esc(error.message)}</p><button type="button" class="btn btn-secondary">Riprova</button>`; target.querySelector('button').onclick = () => renderAdminOverview(target, token, esc); }
}
