export function issueForm(target,{groupId,requestId,user,api,esc}){
 const box=document.createElement('details');box.className='payment-note community-panel';box.innerHTML='<summary>Segnala un problema a BYS</summary><p>Descrivi il problema. BYS riceverà la segnalazione collegata al gruppo; la chat privata non verrà condivisa automaticamente. Le quote dirette non prevedono un rimborso automatico BYS.</p>'+(user?'<form><label>Cosa è successo?<textarea name="description" required minlength="10" maxlength="2000" style="width:100%"></textarea></label><button class="btn btn-secondary">Invia segnalazione</button><p role="status"></p></form>':'<a href="#login">Accedi per segnalare</a>');target.append(box);
 if(user)box.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/api/manual/community/issues',{groupId,requestId,description:new FormData(e.target).get('description')});box.querySelector('[role="status"]').textContent='Segnalazione registrata. La trovi nelle tue partecipazioni, sezione Le mie segnalazioni.';}catch(err){box.querySelector('[role="status"]').textContent=err.message;}finally{b.disabled=false;}};
}
export function watchButton(target,{service,groupId,user,api}){const b=document.createElement('button');b.type='button';b.className='btn bys-watch-cta';b.innerHTML='<span aria-hidden="true">🔔</span> Avvisami quando c’è un posto';const status=document.createElement('p');status.setAttribute('role','status');target.append(b,status);b.onclick=async()=>{if(!user){location.hash='#login';return;}b.disabled=true;try{await api('/api/manual/community/watch',{service:typeof service==='function'?service():service,groupId});b.textContent='✓ Avviso attivato';status.textContent='Avviso attivato. Lo riceverai nelle notifiche e, se abilitate, sul dispositivo. Non è una prenotazione.';}catch(e){status.textContent=e.message;b.disabled=false;}};}
export function requirementsBox(target,g,{owner,user,api,esc}){
 const q=g.requirements;const box=document.createElement('section');box.className='payment-note community-panel';box.innerHTML='<h4>Prima di partecipare</h4>'+(q?`<dl><dt>Paese / area</dt><dd>${esc(q.country)}</dd><dt>Accesso al servizio</dt><dd>${esc(q.accessMethod)}</dd><dt>Chi può partecipare</dt><dd>${esc(q.eligibility)}</dd></dl>`:'<p>Requisiti non ancora indicati. Chiedi al capogruppo di completarli prima di richiedere un posto.</p>')+'<p>Controlla che il piano e la tua situazione rispettino le condizioni del servizio.</p>';target.append(box);
 if(owner){const d=document.createElement('details');d.innerHTML=`<summary>Modifica requisiti</summary><form><label>Paese / area<input name="country" maxlength="80" required value="${esc(q?.country||'')}"></label><label>Modalità di accesso<input name="accessMethod" maxlength="120" required value="${esc(q?.accessMethod||'')}"></label><label>Chi può partecipare<textarea name="eligibility" maxlength="600" required>${esc(q?.eligibility||'')}</textarea></label><button class="btn btn-secondary">Salva requisiti</button><p role="status"></p></form>`;box.append(d);d.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await api('/api/manual/groups/'+encodeURIComponent(g.id)+'/requirements',Object.fromEntries(new FormData(e.target)));location.reload();}catch(err){d.querySelector('[role="status"]').textContent=err.message;}};}
}
export function participationProgress(card,r,{user,api,reload,esc}){
 const stage=r.status==='confirmed'&&r.accessReceivedAt?4:({pending:0,accepted:1,reported:2,confirmed:3})[r.status];
 const box=document.createElement('div');box.className='payment-note community-panel';box.innerHTML=r.status==='canceled'?'<p>Partecipazione terminata. Lo storico resta disponibile.</p>':`<ol style="display:flex;flex-wrap:wrap;gap:12px;padding:0;list-style:none">${['Richiesta','Accettata','Pagamento dichiarato','Accredito confermato','Accesso ricevuto'].map((t,i)=>`<li style="font-weight:${stage===i?'700':'400'};color:${i<=stage?'#126649':'#64748b'}">${i<=stage?'✓':'○'} ${t}</li>`).join('')}</ol>`;card.append(box);
 if(r.leaveAtPeriodEnd&&r.status==='confirmed')box.insertAdjacentHTML('beforeend',`<p><strong>Uscita programmata per il ${esc(new Date(r.periodEnd).toLocaleDateString('it-IT'))}.</strong> Il periodo già pagato resta valido.</p>`);
 if(user.id===r.userId&&r.status==='confirmed'){
 for(const [action,label] of [...(!r.accessReceivedAt?[['access-received','Ho ricevuto l’accesso']]:[]),...(Date.parse(r.periodEnd)>Date.now()?[[r.leaveAtPeriodEnd?'keep-place':'schedule-exit',r.leaveAtPeriodEnd?'Annulla uscita programmata':'Lascia il gruppo alla scadenza']]:[])]){const b=document.createElement('button');b.className='btn btn-secondary';b.textContent=label;box.append(b);b.onclick=async()=>{b.disabled=true;try{await api('/api/manual/'+encodeURIComponent(r.id)+'/'+action,{});await reload();}catch(e){b.disabled=false;const p=document.createElement('p');p.textContent=e.message;box.append(p);}};}}
}
export async function communityInbox(target,{api,esc}){const data=await api('/api/manual/community');const section=document.createElement('section');section.className='payment-note';section.innerHTML=`<details><summary>Le mie segnalazioni e gli avvisi</summary><h4>Segnalazioni a BYS</h4>${data.issues.map(x=>`<article><strong>${({open:'Inviata',reviewing:'In gestione',resolved:'Risolta'})[x.status]}</strong><p>${esc(x.description)}</p>${x.reply?`<p>Risposta BYS: ${esc(x.reply)}</p>`:''}</article>`).join('')||'<p>Nessuna segnalazione.</p>'}<h4>Avvisi di disponibilità</h4><div data-watches></div></details>`;target.append(section);for(const w of data.watches){const p=document.createElement('p');p.textContent=w.service+' ';const b=document.createElement('button');b.className='btn btn-secondary';b.textContent='Disattiva avviso';p.append(b);section.querySelector('[data-watches]').append(p);b.onclick=async()=>{b.disabled=true;try{await api('/api/manual/community/watch',{service:w.service,groupId:w.groupId,active:false});p.remove();}catch(e){b.disabled=false;p.append(document.createTextNode(e.message));}};}if(!data.watches.length)section.querySelector('[data-watches]').textContent='Nessun avviso attivo.';}
